app/code/community/Taxjar/SalesTax/Model/Smartcalcs.php

This PR fixes calculations for bundle products with fixed pricing.
**Dynamic pricing** includes the unit price for both the bundle product and its associated simple products, which would add the amount multiple times if we didn't skip the base product.
**Fixed pricing** includes the unit price for just the bundle product, so we need to make sure it's included when building out the line items. The associated products have a $0 unit price so they're not included.

Fixed Price Bundle Product Calculations

---

modman

Modman mapping has a missing directory, so when doing composer installs/updates not everything is mapped. 
This PR fixes the problem.

Added missing template modman mapping

---

app/code/community/Taxjar/SalesTax/Model/Observer/ImportRates.php

This fixes a PHP7 error when the TaxJar Magento cronjob is calling `Taxjar_SalesTax_Model_Observer_ImportRates->execute()`.
```
PHP Fatal error: Uncaught TypeError: Argument 1 passed to Taxjar_SalesTax_Model_Observer_ImportRates::execute() must be an instance of Varien_Event_Observer, instance of Mage_Cron_Model_Schedule given, called in /var/www/html/app/code/core/Mage/Cron/Model/Observer.php on line 326 and defined in /var/www/html/app/code/community/Taxjar/SalesTax/Model/Observer/ImportRates.php:29
```

Fixed PHP7 type error when import rates is called from cron

---

app/code/community/Taxjar/SalesTax/Model/Observer/ImportRates.php

The ZIP code validation regex was not anchored, so it would match any string which contains 5 digits, eg `foo12345bar`.
Fixed it by adding start (`^`) and "end" (`$`) of string anchors.

Fixed zip validation regex

---

app/code/community/Taxjar/SalesTax/Model/Observer/ImportRates.php

There was a syntax error in PR #16 regex. This fixes that.
Didn't properly copy the changes over from our working branch. Sorry about that.

Fixed syntax error in zip validation regex

---

app/code/community/Taxjar/SalesTax/Model/Sales/Total/Quote/Tax.php
app/code/community/Taxjar/SalesTax/Model/Smartcalcs.php

This PR resolves #13 by using the item index rather than its ID, which may not be set when:
- Customer is logged in or they have a zip code in their checkout session
- **Configuration > Sales > Checkout > After Adding a Product Redirect to Shopping Cart** is turned off for the Magento store
- Item is then added to the cart
#14 introduced the original fix, but we have some special logic in place to handle Magento bundle products via `getAllItems` and I wanted to simplify.

Fix tax on newly added cart items

---

app/code/community/Taxjar/SalesTax/Model/Comment.php

This PR ensures the `reporting_access` param is passed to our extension for determining whether transaction sync can be enabled. Once fixed, merchants already on a paid subscription or trial won't have to re-authenticate to unlock transaction sync.

SmartCalcs Connect Reporting Access Fix

---

app/code/community/Taxjar/SalesTax/Model/Categories.php

When choosing a TaxJar Category for Product Tax Classes, the "None"
category was confusing users who mistakenly assumed it meant no taxes
would be applied.  Renaming it to "Fully Taxable" should help clarify
the proper use case.

Rename Tax Category "None" to "Fully Taxable"

---

app/code/community/Taxjar/SalesTax/Model/Transaction/Refund.php

This commit checks to ensure line_items are set in the request before
trying to iterate over the array.

Fix empty line items bug - transaction-sync only

---

app/code/community/Taxjar/SalesTax/Model/Tax/Nexus.php

When syncing nexus addresses from TaxJar, ensure the country is set
before saving the address.  If the country is US/Canada, ensure the
state is also set.

Ensure country/state is set when syncing TJ nexus

---

app/code/community/Taxjar/SalesTax/Model/Transaction.php

Because bundle products are a collection of simple products and don't
have their own tax class, they were incorrectly reported with 99999.
Tracking the individual items resolves this and increases transparency.

Change bundle products to report individual items

---

app/code/community/Taxjar/SalesTax/Model/Observer/BackfillTransactions.php
app/code/community/Taxjar/SalesTax/Model/Observer/SyncRefund.php
app/code/community/Taxjar/SalesTax/Model/Observer/SyncTransaction.php
app/code/community/Taxjar/SalesTax/etc/config.xml

This PR creates an observer on the sales_order_payment_refund to sync refunds to TaxJar when it is called.  
It also reworks loading credit memos (in SyncTransactions and BackfillTransactions) to circumvent a caching issue that prevent all credit memos from being loaded in the collection.

Pi 99 sync refund event

---

app/code/community/Taxjar/SalesTax/Model/Smartcalcs.php
app/code/community/Taxjar/SalesTax/Model/Transaction.php
app/code/community/Taxjar/SalesTax/etc/config.xml
app/code/community/Taxjar/SalesTax/sql/salestax_setup/upgrade-2.4.1-2.4.2.php

Previously products with a tax class of "none" were assigned 99999 to
mark them as tax exempt. This change removes that functionality and
requires users to pick a valid tax class to mark the product as exempt.
The "none" tax class now defaults to fully taxable.

Remove 99999s when product tax class is "none"

---

app/code/community/Taxjar/SalesTax/Model/Transaction/Refund.php

When issuing a refund, the items passed to _buildLineItems() where
Order_Creditmemo_Item instead of the expected Order_Item.  This caused
$itemType in Model/Transaction.php to be null and 99999 reported as
the tax class.  Looking up the Order_Items resolves this.

Pi 176 bundle product credit memo 99999

---

app/code/community/Taxjar/SalesTax/data/salestax_setup/data-upgrade-2.4.2-2.4.3.php

Data upgrade 2.4.2-2.4.3 makes a call to the categories endpoint but was
returning a 404 due to an error.

Fix broken call to categories endpoint

---

app/code/community/Taxjar/SalesTax/Block/Adminhtml/Tax/Class/Edit/Form.php
app/code/community/Taxjar/SalesTax/Model/Observer/ImportCategories.php
app/code/community/Taxjar/SalesTax/Model/Resource/Tax/Category.php
app/code/community/Taxjar/SalesTax/Model/Resource/Tax/Category/Collection.php
app/code/community/Taxjar/SalesTax/Model/Tax/Category.php
app/code/community/Taxjar/SalesTax/controllers/Adminhtml/TaxjarController.php
app/code/community/Taxjar/SalesTax/data/salestax_setup/data-upgrade-3.0.0-3.0.1.php
app/code/community/Taxjar/SalesTax/etc/config.xml
app/code/community/Taxjar/SalesTax/sql/salestax_setup/upgrade-3.0.0-3.0.1.php

Storing product tax categories as a configuration value won't scale well
as we continue to increase the total number of categories. Reworking
categories to be stored in their own table eliminates this problem and
will support significantly more categories.

Rework product tax category storage

---

app/code/community/Taxjar/SalesTax/Model/Transaction.php
app/code/community/Taxjar/SalesTax/Model/Transaction/Order.php
app/code/community/Taxjar/SalesTax/Model/Transaction/Refund.php

When syncing orders/refunds to TaxJar, first check to see if the M2ePro order class
exists.  If so, try to load the original provider from the order.

Improve support for M2E Pro

---

app/code/community/Taxjar/SalesTax/Helper/Data.php
app/code/community/Taxjar/SalesTax/Model/Client.php
app/code/community/Taxjar/SalesTax/Model/Smartcalcs.php

This change increases the information we gather for specific user server setups to aid in debugging problems. 
Add a custom user agent string to API requests.  UA includes information about the operating
system, php version, curl version, openSSL version, Magento version and version of the TaxJar
extension currently installed.
Modifying the string passed along in the http_user_agent field should have no impact on performance.
1.  Trigger any call to TaxJar's api (tax calculation, transaction sync, address validation, etc).
2. Confirm the "http_user_agent" string matches the data from the server it was tested from.

Add a custom user agent string to API requests

---

app/code/community/Taxjar/SalesTax/Model/Smartcalcs.php

Update the gift card tax code from '99999' to '14111803A0001'
Updates the default gift card tax code from '99999' to '14111803A0001' for improved accuracy.
Gift cards used as part of Magento Commerce previously used '99999' to mark them exempt. Using '14111803A0001' is more accurate.
This change has no affect on performance, as we're only changing the tax code that is sent to the API.
1. Add a gift card to Magento's shopping cart (note: gift cards are only available in Commerce and B2B editions of Magento)
2. Visit the shopping cart page and enter a city and zip code to estimate taxes.
3. Confirm that no taxes were calculated for the gift card.

Update the gift card product tax code

---

app/code/community/Taxjar/SalesTax/Model/Client.php
app/code/community/Taxjar/SalesTax/Model/Transaction.php
app/code/community/Taxjar/SalesTax/Model/Transaction/Order.php
app/code/community/Taxjar/SalesTax/Model/Transaction/Refund.php

Currently error messages returned by the API are ignored in favor of predefined error messages.  This change logs API error messages during transaction sync and adds the option to fall back to default messaging when desired.
This PR allows logging API specific errors during transaction sync.  
This PR should have no change to performance.  
1.  Create, invoice and ship an order so that it syncs to TaxJar
2. Force an error to occur.  For example, **temporarily** modify the subtotal to an invalid amount in Taxjar_SalesTax_Model_Transaction_Order:
`$subtotal = (float) $order->getSubtotal() * 2;`
3.  Attempt to backfill the transactions and confirm that the specific error message is reported.

Improve error handling during transaction sync

---

app/code/community/Taxjar/SalesTax/Model/Observer/ImportCategories.php
app/code/community/Taxjar/SalesTax/Model/Resource/Tax/Category/Collection.php
app/code/community/Taxjar/SalesTax/sql/salestax_setup/upgrade-3.0.1-3.0.2.php

This PR removes the plus_only flag from the product tax categories.  
The plus_only feature is no longer used and is being removed.  
This change has a negligible impact on performance.  
1. Clear the configuration cache from the admin to ensure the extension's setup version is upgraded to 3.0.2.  
2. Ensure the 'plus_only_ column is removed from the table 'tj_product_tax_categories'.
3. Ensure the "PLUS ONLY" label is removed from the Product Tax Class list of categories (click the select element "TaxJar Category" to expand it).

Remove plus_only field from PTCs

---

app/code/community/Taxjar/SalesTax/Model/Smartcalcs.php
app/code/community/Taxjar/SalesTax/Model/Transaction.php

This PR standardizes all address usage to only use the first line of the street.  
In the above image, "Third Floor" should be omitted when determining the address.  
This PR has no impact on performance.  
1. Setup a shipping origin address with multi-streets
2. Create an order with a multi-street shipping address
3. Confirm that only the first line of each street is used when calculating taxes and syncing transactions to TaxJar

Use the first street in multi-street addresses

---

app/code/community/Taxjar/SalesTax/Model/Observer/AdminMenuItems.php
app/code/community/Taxjar/SalesTax/Model/Observer/SyncRefund.php
app/code/community/Taxjar/SalesTax/Model/Observer/SyncTransaction.php
app/code/community/Taxjar/SalesTax/Model/Transaction/Comment.php
app/code/community/Taxjar/SalesTax/Model/Transaction/Order.php

The transaction sync setting only checks the default store scope.  This change supports loading the current store scope value.  
When checking to see if transaction sync is enabled, pass the current store id to load the value for that store.
1. Configure Magento to use multiple stores
2. Enable transaction sync for the default store, but disable it for a specific store
3. Place an order on that store, invoice and ship it.  Confirm that the order does not sync to TaxJar

Change the "transaction sync" setting to use scope
